[deps]
CSV = "336ed68f-0bac-5ca0-87d4-7b16caf5d00b"
DataFrames = "a93c6f00-e57d-5684-b7b6-d8193f3e46c0"
KuMo = "b681f84e-bd48-4deb-8595-d3e0ff1e4a55"
PGFPlotsX = "8314cec4-20b6-5062-9cdb-752b83310925"
StatsPlots = "f3b207a7-027a-5e70-b257-86293d7955fd"
